- hosts: couchdb
  tasks:
    - name: ensure    systemctl is at the latest version
      apt: name=systemctl state=latest
    - name: ensure    debconf-utils is at the latest version
      apt: name=debconf-utils state=latest
    - name: ensure curl is at the latest version
      apt: name=curl state=latest
    - name: ensure apt-transport-https is at the latest version
      apt: name=apt-transport-https state=latest
    - name: ensure gnupg is at the latest version
      apt: name=gnupg state=latest
